### ISSUE TITLE
NPM Package tsconfig.json is broken

### ISSUE THREAD

**Issue by drew-y** [cspotcode/outdent#10]
When outdent is installed in a typescript project the compiler complains of a configuration issue in the package.

The error is:
`[ts] The specified path does not exist: 'node_modules/outdent/tsconfig-test.json'.`

This line in tsconfig.json seems to be the culprit:

`"extends": "./tsconfig-test.json",`

tsconfig-test.json is not included in the package. 

A quick fix would be to include that file in the package. Usually this would be done in the `.npmignore` file.

**Comment by cspotcode** [comment]
Interesting; I didn't know TypeScript would ever look at that
tsconfig.json.  Does your project have its own tsconfig.json?

**Comment by drew-y** [comment]
I should clarify that this isn't throwing an error when I compile my project. The typescript language server is just complaining about it in VSCode. Which causes the package to be highlighted in red in VSCode, indicating an error. Not a big deal, but it's mildly annoying and should be a quick fix.

**Comment by drew-y** [comment]
Yes. Here is a copy of it if you're interested:

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./src",
    "outDir": "./dist",
    "strict": true
  }
}
```

**Comment by drew-y** [comment]
It appears that a [good practice](https://stackoverflow.com/questions/30928253/writing-npm-modules-in-typescript)* is to add `tsconfig.json` to the `.npmignore` file. It'll reduce the size of the release marginally and it'll prevent certain editors like vscode from getting confused.

*See answers 2 & 3

Thanks for the helpful package!

**Comment by cspotcode** [comment]
Thank you for reporting this, and sorry for the delayed response.

I ended up fixing the problem in v0.6.0 by bundling the missing tsconfig file instead.  I want to make sure that editors pick up the right settings for "strictNullChecks", etc. whenever someone uses their debugger to step into "outdent".  This is why I bundle the source code as well, even though I know many people choose to avoid this.

If this doesn't solve the problem, let me know and I'll take another look.
