### ISSUE TITLE
Feature request: support `join` option

### ISSUE THREAD

**Issue by scottrippey** [cspotcode/outdent#11]
I would like a "join" option, so that multi-line strings could be both outdented and joined into a single line.  
Examples:
```
example = outdent({ join: " " })`
  This is a
  multiline string
  that is joined with spaces instead of newlines.
`; // "This is a multiline string that is joined with spaces instead of newlines."
```
Or even better:
```
example = outdent(" ")`
  Just specify a string
  to use 'join'.
`; // "Just specify a string to use 'join'."
```

A little backstory, I actually have my own `outdent` function implemented in several projects, and use it constantly!  I found this repo when thinking about publishing my `outdent`.  I'm glad to see it already exists!  
This 'join' feature is something I use quite often, too, so if that's something you supported, I'd probably stop working on my own and "make the switch" to this one!  
Let's discuss?

**Comment by cspotcode** [comment]
Thanks for reaching out.  `join` seems out of scope for this project since
it's unrelated to indentation removal.

You can call `replace(/\r\n|\n|\r/g, joinerString)` on outdent's output and
even precompose this functionality into a custom outdent function.  For
example:

```
function outdentJoiner(joinerString, outdentInstance = outdent) {
    return (...args) => outdentInstance(...args).replace(/\r\n|\n|\r/g,
joinerString);
}

const r = outdentJoiner(' ') `
    Multiline
    String
`;
```

Out of curiosity, what is the use case where you want to preserve relative
indentation (which is what outdent does) while also eliminating all
newlines?  I've never had a situation where the extra spaces or tabs were
relevant without newlines.

```
const r = outdentJoiner(' ') `
    * Markdown list
      1. Nested indentation
      2. Also nested indent
`;
```

**Comment by cspotcode** [comment]
Maybe we can add a `newline` option that allows specifying or normalizing
the newlines.  For example, git repos without a .gitattributes will
checkout all code with CRLF on Windows and LF on Unix.  So it seems useful
for outdent to allow optionally normalizing to one or the other.  And, for
your purposes, you can pass whatever newline string you like.

outdent({newline: ' '}) `
   String here
`;

**Comment by scottrippey** [comment]
I do like the `newline` option, which makes this feature "fit" better with this module.
My primary use-case is simply to break long string templates over multiple lines.
One of my projects is a chat-bot, so I've got to compose lengthy sentences.  Eg:
```
robot.send(outdent(" ")`
  The current version is ${currentVersion},
  and you can update it by saying
  "${robot.name} deploy ${newVersion} to prod".
`);
```
Being able to split up this single-line across 3 lines makes the code FAR more readable!

YAML actually has 9 different ways to write multi-line strings, all designed for maximizing readability.
All of them "strip" the indentation, and then join the strings in different ways.
https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines

**Comment by cspotcode** [comment]
I'm curious, do they strip *all* indentation?  Outdent preserves relative
indentation, so if one line is indented 4 and another 8, the latter will
start with 4 spaces, the former with 0.

**Comment by scottrippey** [comment]
Relative indentation is a great feature, but I have no scenarios where it would be used together with single-line join.
I'd expect, if you use both features, you'd simply end up with the extra space inline.

**Comment by cspotcode** [comment]
Ok cool.  The reason I asked is, if you don't need relative indentation then something as simple as the following will do what you want:

```
inputString.replace(/\s*[\r\n]\s*/g, ' ').trim();
```

However, if someone writes a PR implementing the `newline` feature we discussed, I'm happy to merge and publish it.  For what it's worth, the PR doesn't need to update any of the TypeScript stuff.  It's easy for me to fix the type annotations given a working JS implementation.

**Comment by cspotcode** [comment]
Closing as replaced by #12, where I describe the proposed `newline` feature in detail.
