### ISSUE TITLE
Inaccurate information in README

### ISSUE THREAD

**Issue by thorn0** [cspotcode/outdent#19]
> For example, in the absence of a .gitattributes file, source code checked out on Windows will have '\r\n' newlines. This affects template literals as well. The following example would produce different results on Windows and Linux, but can be normalized via newline:
>```js
>s = outdent `
>    first
>    second
>`;
>
>assert(s === 'first\r\nsecond'); // Only true for git checkout on Windows
>assert(s === 'first\nsecond'); // Only true for git checkout on Linux
>```

That's not how JavaScript works.  See https://www.ecma-international.org/ecma-262/10.0/index.html#sec-static-semantics-tv-and-trv

Or check in the browser console:
```js
eval("`\r\n`") === "\n"  // true
```

**Comment by cspotcode** [comment]
Sweet, sounds good.

**Comment by papb** [comment]
Interesting, I never thought of this. Nice.

**Comment by cspotcode** [comment]
Inaccuracies have been removed.
https://github.com/cspotcode/outdent/blob/master/README.md#newline
