### ISSUE TITLE
"import from" doesn't work

### ISSUE THREAD

**Issue by marcospgp** [cspotcode/outdent#2]
The readme suggests using import instead of require, but none of node's current versions support that.

**Comment by cspotcode** [comment]
Right, you'll have to use a transpiler for that.  I think this tool was
written at a time when VMs didn't natively support template literals, so
the assumption was you'd be using a transpiler.

If you want to submit a PR that improves the README, I'll merge it.

**Comment by cspotcode** [comment]
Resolved by #5.
