### ISSUE TITLE
Named export

### ISSUE THREAD

**Issue by privatenumber** [cspotcode/outdent#21]
Any reason for the [named export](https://github.com/cspotcode/outdent/blob/master/src/index.ts#L214) in addition to the default export?

Getting the following ESlint error:
[eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-named-as-default.md): `Using exported name outdent as identifier for default export.`

The error is caused because the variable name `outdent` in `import outdent from 'outdent';` is used by a named export from the "outdent" package.

**Comment by cspotcode** [comment]
Yeah, named exports are a great way for code editors/language services to write import statements automatically.  Refer to `outdent` in your code and the editor will offer to `import {outdent} from 'outdent';` automatically.

As you probably realized, the fix is simple: `import {outdent} from 'outdent';` or turn off that linter rule since it seems not to be helping.

**Comment by privatenumber** [comment]
Gotcha. Thanks for the prompt explanation.

FYI I use ST3, and it doesn't make that recommendation to me.

Might be worth evaluating the cost-benefits of duplicating exports like this.
I haven't seen this convention before and I can imagine it confusing other forms of static analysis (eg. autocompletes that attempt to derive the default export name from package name).

**Comment by cspotcode** [comment]
Which plugin are you using to enable automatic imports?

As I understand, Sublime leans on plugins for this type of functionality and doesn't bundle any sort of language intelligence, so your experience will depend on the quality of plugin you're using.  Fortunately the JS language service can be embedded in any editor, which allows us to say with some confidence that the experience between decent editors will be similar.

![image](https://user-images.githubusercontent.com/376504/84710978-49870600-af33-11ea-9439-d1527402f123.png)

![image](https://user-images.githubusercontent.com/376504/84711424-53f5cf80-af34-11ea-9627-9fe39e771d79.png)

**Comment by privatenumber** [comment]
Ah thanks for going out of your way to show me that.

I deliberately opt of IDE features like this but maybe I'll try it out this week.

Thanks 🙏
