### ISSUE TITLE
Removing characters from the string if the first line is indented deeper than the following ones

### ISSUE THREAD

**Issue by TimShilov** [cspotcode/outdent#23]
How to reproduce:
```js
const outdent = require('outdent');

// Notice the indent of the first line
const sql = outdent`
                Select 2
                    From (Select day AS _date From days WHERE day BETWEEN ? AND ? Group By 1) As d
     Left Join (
   
   SELECT 1) As c
        On d._date = c._date
        WHERE c._date IS NOT NULL`;

console.log(sql);
```

Expected result:
```
Select 2
    From (Select day AS _date From days WHERE day BETWEEN ? AND ? Group By 1) As d
Left Join (
SELECT 1) As c

On d._date = c._date
WHERE c._date IS NOT NULL
```

Actual result (lost of characters missing resulting in invalid SQL):
```
Select 2
    From (Select day AS _date From days WHERE day BETWEEN ? AND ? Group By 1) As d


c
te = c._date
_date IS NOT NULL
```

I get that it is a weirdly formatted string but I have encountered it in the case where this SQL is composed from multiple variables so it was hard to spot the problem until it happened.
I think `outdent` should only remove indentation and leave all non-whitespace characters in place. It is unexpected that removing indents from SQL results in invalid SQL.

**Comment by cspotcode** [comment]
There's a feature to support this use-case in the README, check for the phrase "You can explicitly specify the indentation level "

**Comment by cspotcode** [comment]
Closing for now; we can re-open if appropriate.
